### PR TITLE
NG Textures colorspace conversion

### PR DESCRIPTION
**Pull request by Cephalobyte**
List of tweaked textures
- PaintedMetalColorable_ng.TIF :                   Non-Color > sRGB
- BraidedSteel_ng.TIF :                                      sRGB > Non-Color
- RustyMetal_ng.TIF :                                        Non-Color > sRGB
- RustyMetalScratched_ng.TIF :                      Non-Color > sRGB
- ClothStripe_ng.TIF :                                         Non-Color > sRGB
- HydrogenThrusterConePlates_ng.TIF :       sRGB > Non-Color
- HydrogenThrusterInjector_ng.TIF :              sRGB > Non-Color
- Atlas4_Colorable_ng.TIF :                              sRGB > Non-Color
- Atlas4_Chrome_ng.TIF :                                 sRGB > Non-Color

Replaced textures from materials
- TransparentScreenArea :                                Chrome_ng.TIF (Non-Color) > HoloScreen_ng.TIF (Non-Color)
- TransparentScreenArea90 :                           Chrome_ng.TIF.001 (Non-Color) > HoloScreen_ng.TIF (Non-Color)
- TransparentScreenArea180 :                         Chrome_ng.TIF.002 (Non-Color) > HoloScreen_ng.TIF (Non-Color)
- TransparentScreenArea270 :                        Chrome_ng.TIF.003 (Non-Color) > HoloScreen_ng.TIF (Non-Color)
- TransparentScreenArea_Outside :               Chrome_ng.TIF.004 (Non-Color) > HoloScreen_ng.TIF (Non-Color)

### CODE REVIEW

**Comment by Cephalobyte** [comment]
On certain materials, normal textures were baked with a Linear/Non-Color colorspace. If opened like a regular normal map (with an sRGB > Non-Color conversion), they appear lighter and therefore, messes up the normals' display.
For example, rotating the UV map would also change lighting.
I've gone through all of them and changed their colorspace to match their correct appearance in-game.

**Comment by Cephalobyte** [comment]
## Omitted texture replacement from materials, found and replaced missing files with relative paths instead

**Comment by enenra** [comment]
We'll need to discuss this further but I'm definitely up for introducing your fixes. It'll just have to be in the version after the one I'm putting together right now. 👍

**Comment by enenra** [comment]
I've implemented this into the files via this commit: https://github.com/enenra/seut-assets/commit/d3191debe98ac71d27595d57c2ca823ba7188f24

Unfortunately I'd already changed a bunch of things so it wasn't possible to merge the PR itself.

**Pull request closed without merging**
